### ISSUE TITLE
using custom allocator

### ISSUE THREAD

**Issue by soliton4** [cisco/openh264#2087]
i would like to use my own allocator for the frame result buffers.
is it possible?

**Comment by sijchen** [comment]
it does not support that at present.

**Comment by cucurbita** [comment]
Hello, 

if I may ,about your "mem align allocator" or supposed ; would be more efficient to use what the platform offers in this matter rather than this naive pointer arithmetic and inane padding ; no offense taken, the author of this allocator lives in the unicorn/lala land or a hippie camp maybe.

Kind Regards.

**Comment by soliton4** [comment]
it that was meant as an insult you didnt do the best job.

the reason i would like to use my own allocator is to use memory that is pre-allocated by javascript.

**Comment by cucurbita** [comment]
Hello, 

it was not about your custom allocator particularly ; neither an insult, just cynicism about the "WelsAllocator" implementation ; logic is not what you think but how it is.

Kind Regards.

**Comment by soliton4** [comment]
i recommend sticking to positive contributions in the future

**Comment by cucurbita** [comment]
Hello, this is a positive contribution: the WelsAllocator should be changed to use platform specific ; its implementation is speculative and tight up to a compiler behavior.

Kind Regards.

**Comment by cartercin22** [comment]
Fuck off whore

**Comment by ruil2** [comment]
@soliton4  we appreciate that you would like to contribute your code in the future. suggestion and code contribution are welcome.
