### ISSUE TITLE
Firefox  "Ask to Activate" not available

### ISSUE THREAD

**Issue by marksjc** [cisco/openh264#2133]
For safety reasons, I have nearly all add-ons in Thunderbird set to "Ask to Activate", but that choice is not given for openH264.  That leaves "Always Activate" or "Never Activate".  I presume this is a Firefox implementation issue, and will check with Mozilla, but asking here in the case that the openh264 code as written precludes activate on demand from browser.  For Firefox, this generally is a message at the bottom of all toolbars, where the user has choices like "activate for session" "activate always" "do not activate".

**Comment by iamzam** [comment]
I am also interested in setting "Ask to Activate" for this and all plug-ins. This should be the standard for any type of rich media add-on because it is an important security issue.  I am also curious to the reasoning behind the binary modules that Cisco has apparently bundled into this open source project.  Why not open source the bundles as well?

/rant

**Comment by jesup** [comment]
The full source is available and tagged, and the binaries are built from that source directly and signed.

Ask-to-activate is problematic in a WebRTC context, which is time-sensitive unlike streaming media and Flash, etc.  Cisco packaging it as a download (instead of Mozilla compiling it into the browser) means that Mozilla is not required to pay royalties, as Cisco is paying them.  If royalties were a non-issue, and H.264 (at least baseline) were free-to-distribute, Mozilla would compile this into the browser as all other current browsers do.

If you don't want to use H.264 with WebRTC, set it to Never Activate.  You can always change it if you want.

**Comment by marksjc** [comment]
Thank you for the quick and cogent reply.  As a complete non-techy, that explanation makes sense to me.  I was mainly curious about the difference compared to other extensions, more as information not critique. 
Thank you again,  the question about open source was not mine but thank you for that,  as well. 

Mark




-------- Original Message --------

**Comment by luser** [comment]
This seems like this is not actually a bug on openh264, but in Firefox's usage of it (even if it might be WONTFIX there).
