### ISSUE TITLE
It is impossible that I use the OpenH264 binary in Andoird/x86 without patent fee paying?

### ISSUE THREAD

**Issue by suzukiplan** [cisco/openh264#2404]
I asked because there is no Android/x86 binary URL in the following:
https://github.com/cisco/openh264/blob/master/RELEASES

_*Android/arm64bit also_

**Comment by theoxuan** [comment]
@suzukiplan Use OpenH264 is legal in the USA as Cisco is paying on your behalf. While software companies outside the USA need not pay anything to to MPEG-LA for developing encoders or decoders whether open-source or closed source.

**Comment by suzukiplan** [comment]
> While software companies outside the USA need not pay anything to to MPEG-LA for developing encoders or decoders whether open-source or closed source.

I think it not be there, because H.264/AVC contains many patent licenses (not only USA).
http://www.mpegla.com/main/programs/AVC/Documents/avc-att1.pdf

**Comment by gonzalezStudec** [comment]
The root problem is that cisco developers provide only one version of the library to their website http://ciscobinary.openh264.org, whereas they should be able to provide the other ones (arm64bit and so on).
I'm wondering why do cisco guys only provide this version?
If this is time consuming, I can compile for other versions, and provide binaries in order to make them available onto the ciscobinary website.

If this is a problem of stability, why not providing a "folder architecture" on ciscobinaries such as:
http://ciscobinary.openh264.org/**v1.5/experimental**/libopenh264-1.5.0-android_arm64bits.so.bz2

**Comment by fluffy** [comment]
This is the same issue as https://github.com/cisco/openh264/issues/2502 . Check out the thread there. If there was an an easy way to do this, I think it would be possible for Cisco to distribute binaeis for other architectures including arm x86 32 and 64 bit.
