### ISSUE TITLE
Got the encDemo crashed on iOS

### ISSUE THREAD

**Issue by fastxyf** [cisco/openh264#2434]
Test environment:
openh264 version : 1.4,1.5, 1.51
iOS version: 9.3
iOS Device: iPhone 5s, iPhone 6S

Test step:
1. Open codec/build/iOS/enc/encDemo/encDemo.xcodeproj
2. Disable AutoTestEnc(), 
  /*
  if (AutoTestEnc() == 0)
    NSLog (@"Auto testing running sucessfully");
  else
    NSLog (@"Auto testing running failed");
  abort();*/
3.Run encDemo , click Simple Encode Test,

APP crash, EXC_BAD_ACCESS, block in this line:pfDeblocking->pfLumaDeblockingLT4Hor (pPix, iStride, iAlpha, iBeta, iTc);

#0	0x000000010013d93c in DeblockLumaLt4H_AArch64_neon ()
#1	0x00000001001067ac in WelsEnc::FilteringEdgeLumaV(WelsEnc::tagDeblockingFunc*, WelsEnc::TagDeblockingFilter*, unsigned char*, int, unsigned char*) at /Users/Joe/temp/openh264-1.4.0/codec/encoder/core/src/deblocking.cpp:260
#2	0x0000000100106cf8 in WelsEnc::DeblockingInterMb(WelsEnc::tagDeblockingFunc*, WelsEnc::TagMB*, WelsEnc::TagDeblockingFilter*, unsigned char (*) [4][4]) at /Users/Joe/temp/openh264-1.4.0/codec/encoder/core/src/deblocking.cpp:397
#3	0x0000000100107cf4 in WelsEnc::DeblockingMbAvcbase(WelsEnc::TagWelsFuncPointerList*, WelsEnc::TagMB*, WelsEnc::TagDeblockingFilter*) at /Users/Joe/temp/openh264-1.4.0/codec/encoder/core/src/deblocking.cpp:651
#4	0x0000000100107e30 in WelsEnc::DeblockingFilterFrameAvcbase(WelsEnc::TagDqLayer*, WelsEnc::TagWelsFuncPointerList*) at /Users/Joe/temp/openh264-1.4.0/codec/encoder/core/src/deblocking.cpp:684
#5	0x00000001001344a0 in WelsEnc::WelsEncoderEncodeExt(WelsEnc::TagWelsEncCtx*, SFrameBSInfo*, Source_Picture_s const*) at /Users/Joe/temp/openh264-1.4.0/codec/encoder/core/src/encoder_ext.cpp:4098
#6	0x000000010012b46c in WelsEnc::CWelsH264SVCEncoder::EncodeFrameInternal(Source_Picture_s const*, SFrameBSInfo*) at /Users/Joe/temp/openh264-1.4.0/codec/encoder/plus/src/welsEncoderExt.cpp:402
#7	0x00000001000ec90c in ProcessEncoding(ISVCEncoder*, int, char**, bool) at /Users/Joe/temp/openh264-1.4.0/codec/console/enc/src/welsenc.cpp:855
#8	0x00000001000ece0c in ::EncMain(int, char **) at /Users/Joe/temp/openh264-1.4.0/codec/console/enc/src/welsenc.cpp:1031
#9	0x00000001000e56b8 in -[ViewController buttonPressed:] at /Users/Joe/temp/openh264-1.4.0/codec/build/iOS/enc/encDemo/encDemo/ViewController.m:78
#10	0x0000000188308ad0 in -[UIApplication sendAction:to:from:forEvent:] ()
#11	0x0000000188308a4c in -[UIControl sendAction:to:forEvent:] ()
#12	0x00000001882f0740 in -[UIControl _sendActionsForEvents:withEvent:] ()
#13	0x000000018830833c in -[UIControl touchesEnded:withEvent:] ()
#14	0x0000000188307f6c in -[UIWindow _sendTouchesForEvent:] ()
#15	0x0000000188300b08 in -[UIWindow sendEvent:] ()
#16	0x00000001882d0f4c in -[UIApplication sendEvent:] ()
#17	0x00000001882cf528 in _UIApplicationHandleEventQueue ()
#18	0x000000018313d124 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#19	0x000000018313cbb8 in __CFRunLoopDoSources0 ()
#20	0x000000018313a8b8 in __CFRunLoopRun ()
#21	0x0000000183064d10 in CFRunLoopRunSpecific ()
#22	0x000000018494c088 in GSEventRunModal ()
#23	0x0000000188339f70 in UIApplicationMain ()

**Comment by HaiboZhu** [comment]
Thanks for your support. We will check it ASAP.

**Comment by dchakarov-broadsoft** [comment]
May be I have similar crash.
I believe that the problem is related with the latest XCode and latest SDK. 

I have tested on environment:
openh264 version : 1.4,1.5
iPhone 6 plus iOS 8.3
iPad Air2 iOS 8.4, 
iPhone 6s plus iOS 9.3, 
iPhone 6s plus iOS 9.3.1

!!! Important !!!
The crash is on devices with arm64 architecture and openh264 for arm64.
On devices with armv7 openh264 is working.
@fastxyf  can you test with iPhone 4s/5/5c or the other device with armv7?


My crash is in:
#0	0x000000010095e0d0 in DeblockLumaEq4H_AArch64_neon ()
#1	0x00000001008ebd78 in WelsEnc::DeblockingInterMb(WelsEnc::tagDeblockingFunc*, WelsEnc::TagMB*, WelsEnc::TagDeblockingFilter*, unsigned char (*) [4][4]) ()
#2	0x00000001008ece3c in WelsEnc::DeblockingMbAvcbase(WelsEnc::TagWelsFuncPointerList*, WelsEnc::TagMB*, WelsEnc::TagDeblockingFilter*) ()
#3	0x00000001008ecf78 in WelsEnc::DeblockingFilterFrameAvcbase(WelsEnc::TagDqLayer*, WelsEnc::TagWelsFuncPointerList*) ()
#4	0x00000001008f719c in WelsEnc::WelsEncoderEncodeExt(WelsEnc::TagWelsEncCtx*, SFrameBSInfo*, Source_Picture_s const*) ()
#5	0x000000010091f02c in WelsEnc::CWelsH264SVCEncoder::EncodeFrameInternal(Source_Picture_s const*, SFrameBSInfo*) ()


Something interesting that I haven't seen before is this  warning in the build log:
codec/decoder/core/src/rec_mb.cpp:246:59: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
  iFullMVx = WELS_CLIP3 (iFullMVx, ((-PADDING_LENGTH + 2) << 2), ((pMCRefMem->iPicWidth + PADDING_LENGTH - 19) << 2));
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./codec/common/inc/macros.h:197:41: note: expanded from macro 'WELS_CLIP3'
#define WELS_CLIP3(iX, iY, iZ) ((iX) < (iY) ? (iY) : ((iX) > (iZ) ? (iZ) : (iX)))
                                        ^~

**Comment by dchakarov-broadsoft** [comment]
When I build openh264 DEBUG: make DEBUGSYMBOLS=True BUILDTYPE=Debug OS=ios ARCH=arm64

The encoder doesn't crash.

**Comment by fastxyf** [comment]
@dchakarov-broadsoft i has test with iPhone4, encoder is work fine.
Test environment:
openh264 version : 1.4,1.5, 1.51
iOS version: 7.1.2
iOS Device: iPhone 4

This crash is happen in arm64 device.

**Comment by fastxyf** [comment]
I has test in iPhone 5s, and iPhone 6s, iOS version crash BUG has fixed.

But MAC version also got a crash.
WelsCopy16x16_sse2:
    0x100142df0 <+0>:   pushq  %r8
    0x100142df2 <+2>:   pushq  %r9
    0x100142df4 <+4>:   leaq   (%rsi,%rsi,2), %r8
    0x100142df8 <+8>:   leaq   (%rcx,%rcx,2), %r9
    0x100142dfc <+12>:  movdqa (%rdx), %xmm0
    0x100142e00 <+16>:  movdqa (%rdx,%rcx), %xmm1
    0x100142e05 <+21>:  movdqa (%rdx,%rcx,2), %xmm2
    0x100142e0a <+26>:  movdqa (%rdx,%r9), %xmm3
    0x100142e10 <+32>:  leaq   (%rdx,%rcx,4), %rdx
    0x100142e14 <+36>:  movdqa (%rdx), %xmm4
    0x100142e18 <+40>:  movdqa (%rdx,%rcx), %xmm5
    0x100142e1d <+45>:  movdqa (%rdx,%rcx,2), %xmm6
    0x100142e22 <+50>:  movdqa (%rdx,%r9), %xmm7
    0x100142e28 <+56>:  leaq   (%rdx,%rcx,4), %rdx
    0x100142e2c <+60>:  movdqa %xmm0, (%rdi)
->  0x100142e30 <+64>:  movdqa %xmm1, (%rdi,%rsi) EXC_BAD_ACCESS(code=1,address=0xd110d86600)
    0x100142e35 <+69>:  movdqa %xmm2, (%rdi,%rsi,2)
    0x100142e3a <+74>:  movdqa %xmm3, (%rdi,%r8)

I use h264enc, found  "Segmentation fault: 11".
Test step:
1.install nasm 
nasm -v
NASM version 2.12 compiled on Apr  1 2016
2. download 
download openh264
git clone -b openh264v1.5.1 https://github.com/cisco/openh264.git
cd openh264

apply iOS patch "add missing sign extension for arm64 on deblocking_aarch64_neon.S "
3. Build
make ENABLE64BIT=Yes

4.Test
cd testbin
../h264enc welsenc.cfg
Segmentation fault: 11

**Comment by ruil2** [comment]
"a4e71d6662bf806e6fc55ff5d4b2ec6743dae1e3 " commit had fixed this issue. you can the latest openh264 code from the master or cherry-pick this commit. thanks!

**Comment by dchakarov-broadsoft** [comment]
iOS crash is fixed! 
Thanks!

**Comment by voipam** [comment]
The same issue is true for x86_64 simulator

**Comment by weizhenwei** [comment]
I updated the codebase and solved my crash,  Thank you @ruil2
