### ISSUE TITLE
inexplicable hash change to 1.6.0 tar.gz release

### ISSUE THREAD

**Issue by JCount** [cisco/openh264#2528]
The sha256 hash for release openh264-1.6.0.tar.gz seems to have change from 951109b86cf82be7d2aa65e7542edf4bdf26ae9ec93674c638d28c02a9d1a59a to 65d307bf312543ad6e98ec02abb7c27d8fd2c9740fd069d7249844612674a2c7 .

Is this an unintentional, secondary result of an action such as retagging, or is there some greater significance, from slight revisions for example?

**Comment by ilovezfs** [comment]
@ HaiboZhu do you know the answer to this? I'm one of the homebrew maintainers and the one in particular who bumped the formula to 1.6.0. It would be helpful to understand why the checksum was changed after we shipped 1.6.0, especially so we know whether we need to regenerate the bottles or not.

**Comment by ilovezfs** [comment]
CC @HaiboZhu do you know the answer to this?

**Comment by HaiboZhu** [comment]
Hi, all, the sha256 hash of openh264 changed as we retagged the source code. Here we add a commit #2522 into the openh264v1.6 branch. Thanks for your support on it.

**Comment by ilovezfs** [comment]
@HaiboZhu You're welcome. In the future, do you mind just bumping the version to 1.7.0 or 1.6.1 or 1.6.0.1 instead of retagging?

**Comment by ilovezfs** [comment]
i.e., create a new tag (we always need a tag) instead of destroying and recreating the original? Alternatively, if you leave the original tag alone, we can always apply a sequence of commits as patches if it's not convenient for you to actually create a new tag. Of course, our preference is always to distribute a fixed tag with zero patch commits whenever possible, so new tags are much appreciated whenever there are important back ports, etc.

**Comment by HaiboZhu** [comment]
@ilovezfs Thanks for your suggestions. We will improve this process and make it more effective later.

**Comment by ilovezfs** [comment]
@HaiboZhu you're welcome. Thanks for your attention to this. We're picky about it mainly because we consider changed checksums to be a security issue until we find out what happened.
