### ISSUE TITLE
Deallocation of output decoded data buffer, multiple output buffers

### ISSUE THREAD

**Issue by TimSC** [cisco/openh264#2687]
Are multiple output buffers allowed? I would like to use a ring buffer of ppDst pointers. This allows one thread to do decoding but to allow other threads to get complete frames. Is this safe? (I've tried implementing it and it seems to work...)

Does openh264 remain responsible for deallocating the output buffer? Does this still work if multiple output buffers are used?

Thx :)

**Comment by huili2** [comment]
If different threads are used for decoding and outputting, the output data from decoder should be copied and saved immediately if you want to use it later. 
Openh264 is surely responsible to free the output memory, but it is unknown to you when it is done. That's why you should save the YUV data if you do not use it right after it is available.

**Comment by TimSC** [comment]
@huili2 Thanks!
