### ISSUE TITLE
AVC data from chrome cannot be decoded by openh264

### ISSUE THREAD

**Issue by PeterXu** [cisco/openh264#2881]
As title, AVC data from chrome webrtc are stored locally, but h264dec tool cannot decode it.
Elecard StreamEye can decode and render.

[H264 Data](https://www.moxtra.com/service4/#view/CAEqBVVWVHhSehhDQmdyUUphTTI1UWpDVm1aNVpxN2NqeTKAAbVNkAMU)

**Comment by huili2** [comment]
@PeterXu The PPS data is non-conformance to H264 standard, so the decoder considers it as illegal packet, and refused to decode. Please check how it was generated.

**Comment by PeterXu** [comment]
@huili2 , from Webrtc code, it rewrites the PPS with VUI and others are not clear.

**Comment by HaiboZhu** [comment]
@huili2 The root cause is that the bitstream contains a piece of meaningless data in PPS while the profile IDC is 66. OpenH264 will try to parse it and then mark the PPS invalid, while ffmpeg H.264 decoder will check the profile idc first and then ignore the data. The detailed implementation can refer to ffmpeg source code file "h264_ps.c", function "more_rbsp_data_in_pps()".

**Comment by huili2** [comment]
Yes. Openh264 considers the PPS as illegal, while other decoder may deal with it differently.

**Comment by PeterXu** [comment]
fixed and thanks

**Comment by huili2** [comment]
Welcome~
