### ISSUE TITLE
warning: Slice type too large(21) at first_mb(0)

### ISSUE THREAD

**Issue by anoop4** [cisco/openh264#2931]
Hi,

I get this warning when decoding a h264 bytestream and this results in 0 byte output file
Here is the command line output:

H264 source file name: IDRslice.264
Sequence output file name: op.yuv..
------------------------------------------------------
[OpenH264] this = 0x00000000004C4E50, Warning:slice type too large (21) at first_mb(0)
-------------------------------------------------------
iWidth:         0
height:         0
Frames:         0
decode time:    0.000452 sec
FPS:            0.000000 fps

Am I missing something here ?

**Comment by huili2** [comment]
This information tells there is something error with your bytestream, as slice_type should never be 21. Please check how the bytestream is generated.

**Comment by srijith-vijay** [comment]
Hi, Thanks for the quick reply!
I am assuming this was caused due to an extra byte that I added while combining the IDR fragments.

However, I am still getting the file of size 0 bytes with no content

H264 source file name: IDRslice.264..
Sequence output file name: op.yuv..
------------------------------------------------------
-------------------------------------------------------
iWidth:         0
height:         0
Frames:         0
decode time:    0.006882 sec
FPS:            0.000000 fps
-------------------------------------------------------

Any idea why this is happening? 
Thanks in Advance!

**Comment by srijith-vijay** [comment]
Here is the byte stream that I am trying to decode, stored in the following format:

**0x000001[SPS] 0x000001[PPS]  0x000001[VIDEO FRAME]**

![2018-03-15_14-06-01](https://user-images.githubusercontent.com/14857369/37452338-4938d19a-285a-11e8-9604-a47b73ad1a06.jpg)

**Comment by huili2** [comment]
It sounds nice to add these bytes in-between the data. But did you add all correct bytes here before each NAL? I still guess it is the illegal of the data that made decoding failure.
