### ISSUE TITLE
Which profiles of h264 is already supported.

### ISSUE THREAD

**Issue by zhoupeng0807** [cisco/openh264#3328]
Hi.
   I saw on Cisco's official website that the initial openh264 code only supports the baseline profile of h264, but I found that the latest code already supports the main profile for encoding and decoding. I don’t know if other profiles of h264 are already supported. It is recommended to add the wiki information of the codec.thx..

**Comment by huili2** [comment]
Sorry for late reply.
Yes you are right that baseline profile is fully supported in both encoder and decoder. However, for main profile,  we do not claim on that because only parts of tools in Main profile are supported (like CABAC). That's why we would not add such information in wiki.
Moreover, contributors are doing B-frame decoding support in decoder. You can have a try if interested in.
Thanks again for putting an eye on openh264.
