### ISSUE TITLE
OpenH264 is not installing

### ISSUE THREAD

**Issue by jeffryfisher** [cisco/openh264#3381]
Firefox 88.0.1 claims "OpenH264 Video Codec provided by Cisco Systems, Inc. will be installed shortly." However, it isn't installing. I came to https://www.openh264.org/ to install manually, but that option is not available. I searched at https://addons.mozilla.org to install manually, but it is not there.

I am now unable to use any of the video streaming services that I have already paid for (Peacock was my aim today). Please put a copy of the extension on either your site or the Mozilla site as a workaround for when the "will be installed shortly" process gets stuck.

**Comment by sltrash** [comment]
Hello!
I'm facing the same problem here, did you find a way to install it manually?
Thanks!

**Comment by jeffryfisher** [comment]
Not in this or any later version. My workaround is to fire up an older machine still running Windows 7 pro that has an older version of Firefox that honors my choice not to update automatically. It somehow got earlier versions of the codec and Widevine installed once upon a time, and by preventing all updates I can avoid the installation bug in later versions.

**Comment by GuangweiWang** [comment]
if you want to download openh264 library, you can refer to the [Release](https://github.com/cisco/openh264/releases) page to find the download link.

**Comment by huili2** [comment]
Close this one since no response from asker.

**Comment by iSeiryu** [comment]
This command helped me on Fedora 39
```bash
sudo dnf install gstreamer1-plugin-openh264 mozilla-openh264  
```
From here: https://docs.fedoraproject.org/en-US/quick-docs/openh264/ 

The "OpenH264 Video Codec provided by Cisco Systems, Inc. will be installed shortly." note disappeared after that and YouTube is working as expected now.

**Comment by clnperez** [comment]
thanks @iSeiryu! That got me around this odd situation.

**Comment by spa-dev** [comment]
Just adding to this thread in case it helps anyone. The above command, or perhaps some other driver installations I tried, allowed me to watch YouTube videos on Firefox 137.0 installed via flatpak on Fedora 40. However, Vimeo was still not working with "Player error The player is having trouble". The following command fixed that:

```flatpak install flathub org.freedesktop.Platform.openh264``` 

Then pick the most recent version in the options given in the terminal. FireFox still gives the H264 codec "will be installed shortly" notification, but everything seems to work.

**Comment by LoongAnimation** [comment]
Here's the solution that worked for me: In Firefox on Rocky9, I typed about:addons in the address bar, switched to Plugins, and found OpenH264 Video Codec provided by Cisco Systems, Inc. The three-dot menu on the right led to Always Activate. The page then indicated plugin will be installed shortly, but it froze and wouldn't download automatically.

(This might be due to my personal preference; I unchecked "Update Add-ons Automatically" in the gear icon in the upper right corner of Plugins.) Clicking the gear icon in the upper right corner of the plugin page > Check for Updates immediately triggered the plugin download and installation.

Done.
