### ISSUE TITLE
Cisco-hosted `2.4.1` library reports version `2.4.0`

### ISSUE THREAD

**Issue by torokati44** [cisco/openh264#3728]
The `WelsGetCodecVersion` function, when called in `libopenh264-2.4.1-linux64.7.so` file - as linked from https://github.com/cisco/openh264/releases/tag/v2.4.1 -, returns version `2.4.0.2310`.
Was that built before #3724 perhaps?
This makes it difficult to check/verify that the appropriate version got deployed and loaded.

To make sure the dynamic linker and loader don't pick up any other file with a different version installed on my system, I tested it like this:

<details>

<summary>
Expand...
</summary>

```c
// openh264versiontest.c
#include <stdio.h>
#include <stdlib.h>
#include <dlfcn.h>

#include "codec_api.h"

int main() {
    void *handle = dlopen("./libopenh264-2.4.1-linux64.7.so", RTLD_LAZY);
    OpenH264Version (*WelsGetCodecVersion)(void) = dlsym(handle, "WelsGetCodecVersion");
    OpenH264Version ver = WelsGetCodecVersion();
    printf("OpenH264 version: %d.%d.%d.%d\n", ver.uMajor, ver.uMinor, ver.uRevision, ver.uReserved);
    dlclose(handle);
}
```

`clang openh264versiontest.c -I Downloads/openh264-2.4.1/codec/api/wels/ -o openh264versiontest`

</details>

**Comment by BenzhengZhang** [comment]
Sorry for confusion, it was actually built behind #3707 and before #3724.  The official package of 2.4.1 will be temporarily removed from the shelves until the correct version information is included in the release. Thank you for discovering this issue.

**Comment by mcatanzaro** [comment]
Is this why the 2.4.1 binaries have changed? Can you please confirm that the changes I observed in https://github.com/cisco/openh264/issues/909#issuecomment-1934859156 are expected and not malicious?

It's [causing](https://gitlab.com/freedesktop-sdk/openh264-extension/-/commit/0a9b921ec53e707d313b4b62b57336bd60fb3381#bc688134294e254daf949a259f872272289cab6c) [problems](https://gitlab.com/freedesktop-sdk/openh264-extension/-/issues/19); in the future, it would be better to just release 2.4.2 instead rather than respin existing releases. At the very least, please provide some notice so that we know it's not malicious.

**Comment by torokati44** [comment]
> ... in the future, it would be better to just release 2.4.2 instead rather than respin existing releases. At the very least, please provide some notice so that we know it's not malicious.

Again, I agree 100%.

**Comment by torokati44** [comment]
Also, could you please confirm that the current `2.4.1` binaries are the final hosted ones, and the release should no longer be marked as "pre-release", @BenzhengZhang?

**Comment by mcatanzaro** [comment]
> It's [causing](https://gitlab.com/freedesktop-sdk/openh264-extension/-/commit/0a9b921ec53e707d313b4b62b57336bd60fb3381#bc688134294e254daf949a259f872272289cab6c) [problems](https://gitlab.com/freedesktop-sdk/openh264-extension/-/issues/19);

I am downgrading freedesktop-sdk back to 2.3.1 until Cisco confirms what has happened here ([additional context](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/17698#note_1767332493)).

**Comment by torokati44** [comment]
FWIW it was just Chinese New Year the other day, which may explain the delay in response.

**Comment by BenzhengZhang** [comment]
I can confirm that binary has been officially replaced by Cisco. Please feel free to use it. I have marked it as the latest release and there will be no new changes. @mcatanzaro @torokati44

**Comment by torokati44** [comment]
Closing as supposedly fixed. Thank you!

**Comment by mcatanzaro** [comment]
OK, thanks Benzheng. I will update freedesktop-sdk and GNOME runtimes.

That said, it would be nice if you don't do this again since it breaks existing users. End user systems download the binary directly from Cisco, expecting it to match the original size and hash. We got lucky this time only because we hadn't released the updated OpenH264 to users yet, avoiding a flood of  complaints. In the future, it would be better to just bump the version number and re-release.

**Comment by BenzhengZhang** [comment]
> OK, thanks Benzheng. I will update freedesktop-sdk and GNOME runtimes.
> 
> That said, it would be nice if you don't do this again since it breaks existing users. End user systems download the binary directly from Cisco, expecting it to match the original size and hash. We got lucky this time only because we hadn't released the updated OpenH264 to users yet, avoiding a flood of complaints. In the future, it would be better to just bump the version number and re-release.

Yes, I agree with your suggestion
