### ISSUE TITLE
Error replay videos from Kaltura in Firefox

### ISSUE THREAD

**Issue by voxik** [cisco/openh264#3751]
During replay of videos provided by [Kaltura](https://corp.kaltura.com/), the player stops with error. Running Firefox with `MOZ_LOG="FFmpegVideo:5 GMP:5"`, there is reported the following error as identified by Fedora FF maintainer in the [rhbz#2279849](https://bugzilla.redhat.com/show_bug.cgi?id=2279849):

~~~
[libopenh264 @ 0x7fc27a47c000] [OpenH264] this = 0x0x7fc26878f000, Error:DecodeCurrentAccessUnit()::::::PrefetchPic ERROR, pSps->iNumRefFrames:5.
[libopenh264 @ 0x7fc27a47c000] DecodeFrame failed
~~~

I am observing the issues on internal resources, so I have to apologize in advance that I won't share better reproducer.

~~~
$ rpm -q firefox
firefox-125.0.3-2.fc41.x86_64

$ rpm -q openh264
openh264-2.4.0-2.fc40.x86_64
~~~

CC @stransky

**Comment by mcatanzaro** [comment]
Here is a public reproducer:

https://corp.kaltura.com/video-collaboration-communication/enterprise-video-portal/

Of course, this website might change in the future. But it reproduces the problem today.

**Comment by voxik** [comment]
@mcatanzaro what version of openh264 do you have installed? Because I have just upgraded to `openh264-0:2.4.1-2.fc41.x86_64` and it seems things might be better (although that might be just pure luck)

**Comment by voxik** [comment]
Maybe you might try with https://codecs.fedoraproject.org/openh264/41/

**Comment by mcatanzaro** [comment]
Wow you're right, I have 2.4.0-2.fc40 (the latest version for F40) and it's definitely fixed by 2.4.1-2.fc41. I think this should be closed. It's a downstream problem now, to update F40.

That means this bug must have been fixed by https://github.com/cisco/openh264/commit/4f01c15b2199daf16924caa53f77a52e8b559260 because there are only two significant commits between the upstream 2.4.0 and 2.4.1, and the other one https://github.com/cisco/openh264/commit/fd66e67ac6136aff80b1567488568ba1ed7e8fb8 is already included in the downstream 2.4.0-2.fc40.

**Comment by abitrolly** [comment]
@voxik do you still need commit confirmation, or the bug is fixed? (the reference URL plays ok from FF on F41)

**Comment by voxik** [comment]
The video playback is mostly fine. So I'll rather close this one
