### ISSUE TITLE
License question.

### ISSUE THREAD

**Issue by tino197** [cisco/openh264#943]
Hi.
I have 3 questions about the license term of  using the binaries.
1) I see this:
THIS PRODUCT IS LICENSED UNDER THE AVC PATENT PORTFOLIO LICENSE FOR THE PERSONAL USE OF A CONSUMER OR OTHER USES IN WHICH IT DOES NOT RECEIVE REMUNERATION TO (i) ENCODE VIDEO IN COMPLIANCE WITH THE AVC STANDARD (“AVC VIDEO”) AND/OR (ii) DECODE AVC VIDEO THAT WAS ENCODED BY A CONSUMER ENGAGED IN A PERSONAL ACTIVITY AND/OR WAS OBTAINED FROM A VIDEO PROVIDER LICENSED TO PROVIDE AVC VIDEO.  NO LICENSE IS GRANTED OR SHALL BE IMPLIED FOR ANY OTHER USE.  ADDITIONAL INFORMATION MAY BE OBTAINED FROM MPEG LA, L.L.C. SEE HTTP://WWW.MPEGLA.COM

My question, this text prevent from using the binaries in commercial software as far as i understand it. but in the FAQ you wrote:
We will select licensing terms that allow for this code to be used in commercial products as well as open source projects

2)   The Cisco-provided binary is separately downloaded to an end user’s device, and not integrated into or combined with third party software prior to being downloaded to the end user’s device;

Does that mean that i can not integrate the binaries into the installer so user will download the software installer that will install my files and Cisco binaries by extracting them from the installer like 99.9% of the installers do? 
I.E offline without interent connection?
From what i understand, this term requires that when user install the installer, then the installer will go online to download the binaries - does that true?
Seems strange.
In this case internet connection will be needed when you install the software so installer will download the binaries - and i am not sure i understand from where the installer should download them? from my website?

3)  The end user must have the ability to control (e.g., to enable, disable, or re-enable) the use of the Cisco-provided binary;

Again seems strange, in my commercial software i should give an option to disable  Cisco-provided binary? the end user will not understand what i want from here and if he disable the binaries then the software will not work and be useless.

Again i do not see why one can use Cisco binaries in a commercial software with these terms ...
Seems unreasonable ...

**Comment by TechnikEmpire** [comment]
I think you guys should talk to a lawyer or the MPEG-LA group themselves. If a patent holder, or someone paying fees, provides a patented library to you, then you are covered under the patent use because they are paying for it. As you can see from the website for openh264, Cisco themselves says "we are not passing on our patent fees to you" or something to this effect.

I have a commercial software where I may be leveraging patented codecs provided built into windows. I reached out to MPEG-LA and told them this and asked what kind of fees I'm looking at. They said because I am linking to a library that a patent holder or someone paying the patent fees has provided, my use is covered under their patent use, hence I will owe no fees.

IIRC, Cisco is not only a joint holder in this portfolio, but pays into it as well, just like Microsoft. So if I can distribute a commercial software that relies on linking to Microsoft's patented libraries, then it follows that I can link to Cisco's patented libraries.

I am not a lawyer, I'm just repeating what was communicated to me by a representative of the MPEG-LA group.
