### ISSUE TITLE
Question about bitrate and framerate

### ISSUE THREAD

**Issue by jim12345** [cisco/openh264#970]
Hi.
I am a little confused with the parameters for encoder.
SEncParamExt has this:
oSEncParamExt.fMaxFrameRate
and this;
oSEncParamExt.iTargetBitrate

Whats confuse me is that if i set fMaxFrameRate to be 30 for example then this alone can determine the Bitrate.
Then why there is an option to set the iTargetBitrate then?

Same question here:
	oSEncParamExt.sSpatialLayers[0].fFrameRate = 30.0f;
	oSEncParamExt.sSpatialLayers[0].iSpatialBitrate = 1500000;

and why there is an option to choose bitrate & FrameRate for input and for output.

Hope someone can make me understand this.

Thanks.

**Comment by chuckleplant** [comment]
@jim12345 I believe there is no way to have both constant bitrate and framerate. To do that the encoder should be able to automatically lower encoding quality. 

Right now if we set the `SEncParamExt.bEnableFrameSkip` to false [there is a warning](https://github.com/cisco/openh264/blob/a39c46601d1348c5958d97e20852a34c50553f08/codec/encoder/core/src/encoder_ext.cpp#L242) that tells us that Rate Control is disabled without skipping frames.

Automatically lowering encoding quality rather than framerate would be nice.
